### ISSUE TITLE
ValueError: remaining_argv: ['--model_path', '/home/a/Qwen2-VL-7B-Instruct/']

### ISSUE THREAD

**Issue by wuybo** [QwenLM/Qwen3-VL#165]
启动命令：CUDA_VISIBLE_DEVICES=0,1 swift infer --model_path /home/a/Qwen2-VL-7B-Instruct/ --model_type qwen2-vl-7b-instruct
请大佬指教谢谢：
报错 ：(llm_swift) a@a:~$ CUDA_VISIBLE_DEVICES=0,1 swift infer --model_path /home/a/Qwen2-VL-7B-Instruct/ --model_type qwen2-vl-7b-instruct
run sh: `/home/a/anaconda3/envs/llm_swift/bin/python /home/a/ms-swift-main/swift/cli/infer.py --model_path /home/a/Qwen2-VL-7B-Instruct/ --model_type qwen2-vl-7b-instruct`
[INFO:swift] Successfully registered `/home/a/ms-swift-main/swift/llm/data/dataset_info.json`
[INFO:swift] No vLLM installed, if you are using vLLM, you will get `ImportError: cannot import name 'get_vllm_engine' from 'swift.llm'`
[INFO:swift] No LMDeploy installed, if you are using LMDeploy, you will get `ImportError: cannot import name 'prepare_lmdeploy_engine_template' from 'swift.llm'`
[INFO:swift] Start time of running main: 2024-09-10 11:36:33.352454
[INFO:swift] ckpt_dir: None
[INFO:swift] Due to `ckpt_dir` being `None`, `load_args_from_ckpt_dir` is set to `False`.
[INFO:swift] Setting template_type: qwen2-vl
[INFO:swift] Setting self.eval_human: True
Traceback (most recent call last):
  File "/home/a/ms-swift-main/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/home/a/ms-swift-main/swift/utils/run_utils.py", line 27, in x_main
    raise ValueError(f'remaining_argv: {remaining_argv}')
ValueError: remaining_argv: ['--model_path', '/home/a/Qwen2-VL-7B-Instruct/']

![06643bee72c9a85ab7ef9da028c8d5c](https://github.com/user-attachments/assets/fb87cf30-4e57-4de1-9ff8-0eb66ff315b9)

**Comment by thonglv21** [comment]
```
pip install git+https://github.com/huggingface/transformers.git
pip install pyav qwen_vl_utils
```

Working with `transformers==4.47.0.dev0`; `ms-swift==2.6.0.dev0`; `qwen-vl-utils==0.0.8`
