### ISSUE TITLE
Base64-encoded jpeg sequence doesn't work with VLLM API (Qwen2.5vl works)

### ISSUE THREAD

**Issue by zekunhao1995** [QwenLM/Qwen3-VL#1762]
We would like to pass videos as sequences of jpeg images to reduce overhead. This implementation works correctly with Qwen2.5-VL and other VLMs. However, when switching to Qwen3-VL, this method no longer works.

The following code snippet works correctly with Qwen2.5-VL:
```python
# Encode video as a sequence of jpegs
frames = []
for frame in video:
    buffer = io.BytesIO()
    PIL.Image.fromarray(frame).save(buffer, format="JPEG", quality=95)
    base64_image = base64.b64encode(buffer.getvalue()).decode("utf-8")
    frames.append(base64_image)
video_base64 = "data:video/jpeg;base64," + ",".join(frames)

# Call VLLM OpenAI API
response = client.chat.completions.create(
    model=model_name,
    messages=[
        {
            "role": "user", 
            "content": [
                {"type": "video_url", "video_url": {"url": video_base64}},
                {"type": "text", "text": "Describe the video in detail."},
            ],
        }
    ],
    extra_body={
        "mm_processor_kwargs": {"fps": [video_fps], "do_sample_frames": False},
    },
    temperature=0.7,
    max_tokens=1024,
)
```

With Qwen3-VL 8B, it gets the following error:
```openai.InternalServerError: Error code: 500 - {'error': {'message': "VideoMetadata.__init__() missing 1 required positional argument: 'total_num_frames'", 'type': 'Internal Server Error', 'param': None, 'code': 500}}```

Environment: `vllm/vllm-openai:latest` docker image with `vllm=0.11.0`.

**Comment by ashwaniag** [comment]
Try passing as base64 encoded video instead of list of images.
check this: https://www.alibabacloud.com/help/en/model-studio/vision#43e8d0d9e47n1

**Comment by zekunhao1995** [comment]
> Try passing as base64 encoded video instead of list of images. check this: https://www.alibabacloud.com/help/en/model-studio/vision#43e8d0d9e47n1

base64-encoded mp4 video works. It is just that in some use cases it is faster to use a list of jpegs. Fixing jpeg support can also help align the interface with other VLMs (including Qwen2.5vl). Jpeg sequence is official supported input format for VLLM
[https://docs.vllm.ai/en/v0.9.0/api/vllm/multimodal/video.html#__codelineno-0-159](url).

**Comment by wulipc** [comment]
@zekunhao1995  FYI:  https://github.com/QwenLM/Qwen3-VL/issues/1643#issuecomment-3424492396

**Comment by minostauros** [comment]
@wulipc Could you suggest any workarounds or monkey patches to provide `total_num_frames` to use base64-encoded jpeg sequence?
In my usecase, decoded frames are always available and re-encoding them into base-encoded mp4 is quite inefficient.

**Comment by minostauros** [comment]
Patching vllm `video.py` like bellow and providing fps with `mm_processor_kwargs` gives 400 error.

```python
    def load_base64(
        self, media_type: str, data: str
    ) -> tuple[npt.NDArray, dict[str, Any]]:
        if media_type.lower() == "video/jpeg":
            load_frame = partial(
                self.image_io.load_base64,
                "image/jpeg",
            )

            frames = data.split(",")

            return np.stack(
                [np.asarray(load_frame(frame_data)) for frame_data in frames]
            ), {"total_num_frames": len(frames)} # <- added

        return self.load_bytes(base64.b64decode(data))
```

`
{'error': {'message': "Failed to apply Qwen3VLProcessor on data={'text': '<|vision_start|><|video_pad|><|vision_end|>', 'videos': [ ... (omitted)], shape=(8, 720, 1280, 3), dtype=uint8)]], 'video_metadata': [[VideoMetadata(total_num_frames=8, fps=None, width=None, height=None, duration=None, video_backend=None, frames_indices=None)]]} with kwargs={'fps': 0.1558846453624318, 'do_sample_frames': False}", 'type': 'BadRequestError', 'param': None, 'code': 400}}
`

`
Qwen3VL requires frame timestamps to construct prompts, but the `fps` of the input video could not be inferred. Probably `video_metadata` was missing from inputs and you passed pre-sampled frames. Defaulting to `fps=24`. Please provide `video_metadata` for more accurate results.
`

**Comment by lingcco** [comment]
> 像下面这样修补 vllm`video.py`并提供 fps`mm_processor_kwargs`会导致 400 错误。
> 
>     def load_base64(
>         self, media_type: str, data: str
>     ) -> tuple[npt.NDArray, dict[str, Any]]:
>         if media_type.lower() == "video/jpeg":
>             load_frame = partial(
>                 self.image_io.load_base64,
>                 "image/jpeg",
>             )
> 
>             frames = data.split(",")
> 
>             return np.stack(
>                 [np.asarray(load_frame(frame_data)) for frame_data in frames]
>             ), {"total_num_frames": len(frames)} # <- added
> 
>         return self.load_bytes(base64.b64decode(data))
> `{'error': {'message': "Failed to apply Qwen3VLProcessor on data={'text': '<|vision_start|><|video_pad|><|vision_end|>', 'videos': [ ... (omitted)], shape=(8, 720, 1280, 3), dtype=uint8)]], 'video_metadata': [[VideoMetadata(total_num_frames=8, fps=None, width=None, height=None, duration=None, video_backend=None, frames_indices=None)]]} with kwargs={'fps': 0.1558846453624318, 'do_sample_frames': False}", 'type': 'BadRequestError', 'param': None, 'code': 400}}`
> 
> `Qwen3VL requires frame timestamps to construct prompts, but the``of the input video could not be inferred. Probably`视频元数据`was missing from inputs and you passed pre-sampled frames. Defaulting to`fps=24`. Please provide `视频元数据`for more accurate results.`

请问一下您现在解决这个问题了吗？在我的使用场景里面需要在vllm中对一个视频用帧列表来传入，但目前我没有找到很好的解决办法

**Comment by minostauros** [comment]
Please refer to https://github.com/QwenLM/Qwen3-VL/issues/1643#issuecomment-3631556522 for a monkey patch for this
